language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - PIPV=8
  - PIPV=9
  - PIPV=10
install:
  - pip install tox coveralls
script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION}-pip${PIPV} | tr -d .)
after_success:
  coveralls
